openapi: 3.0.3
info:
  title: Cherry Deploy · Deployment & Rollback API
  version: 1.0.0
  description: |
    Next.js 대상(Repo1)을 Blue/Green 방식으로 배포하거나 직전 성공 커밋으로 롤백합니다.
    모든 엔드포인트는 JWT 쿠키(`auth_token`) 인증이 필요하며, FastAPI BackgroundTask로 실행됩니다.
servers:
  - url: https://delight.13-125-116-92.nip.io
    description: Production (TLS + Nginx)
  - url: http://127.0.0.1:9001
    description: 로컬 FastAPI
components:
  securitySchemes:
    AuthCookie:
      type: apiKey
      in: cookie
      name: auth_token
      description: `/api/v1/auth/login` 에서 발급되는 JWT 쿠키
paths:
  /api/v1/deploy:
    post:
      summary: Next.js 프론트엔드 배포 트리거
      tags:
        - deploy
      security:
        - AuthCookie: []
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/DeployRequest'
            examples:
              default:
                value:
                  branch: deploy
      responses:
        "202":
          description: 배포 작업이 큐에 등록됨
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/DeployResponse'
        "400":
          description: 허용되지 않은 브랜치
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'
        "500":
          description: 서버 오류로 작업 생성 실패
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'
  /api/v1/rollback:
    post:
      summary: 직전 성공 배포로 롤백
      tags:
        - deploy
      security:
        - AuthCookie: []
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/RollbackRequest'
            examples:
              default:
                value:
                  branch: deploy
      responses:
        "202":
          description: 롤백 작업이 큐에 등록됨
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/DeployResponse'
        "400":
          description: 입력 오류
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'
        "409":
          description: 롤백 가능한 성공 이력이 부족
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'
components:
  schemas:
    DeployRequest:
      type: object
      properties:
        branch:
          type: string
          description: 허용된 브랜치(`deploy`, `main`). 생략 시 기본값 사용.
    RollbackRequest:
      type: object
      properties:
        branch:
          type: string
          description: 롤백 대상 브랜치 (선택)
    DeployResponse:
      type: object
      required:
        - task_id
        - status
        - branch
        - action
        - queued_at
        - estimated_duration_minutes
        - context
        - dev_server_restart_planned
      properties:
        task_id:
          type: string
        status:
          type: string
          enum: [pending, running_clone, running_build, running_cutover, running_observability, completed, failed]
        branch:
          type: string
        action:
          type: string
          enum: [deploy, rollback]
        queued_at:
          type: string
          format: date-time
        estimated_duration_minutes:
          type: integer
        context:
          type: object
          additionalProperties: true
        dev_server_restart_planned:
          type: boolean
    ErrorResponse:
      type: object
      properties:
        detail:
          type: string
