openapi: 3.0.3
info:
  title: Cherry Deploy Status API
  version: 0.1.0
  description: |
    Poll deployment progress using the task identifier returned by `/api/v1/deploy`.
    NOTE: Requires the live FastAPI service and MongoDB to be available; this spec alone cannot return task state.
    ⚠️ 전체 API 스펙은 `swagger-api/openapi.yaml`을 사용하세요. 이 파일은 참고용 조각 문서입니다.
servers:
  - url: https://delight.13-125-116-92.nip.io
    description: Production-like endpoint (HTTPS via Let's Encrypt)
  - url: http://127.0.0.1:9001
    description: Local FastAPI server (bypasses Nginx)
paths:
  /api/v1/status/{task_id}:
    get:
      summary: Fetch current deployment status
      operationId: getDeployStatus
      tags:
        - deploy
      parameters:
        - in: path
          name: task_id
          required: true
          schema:
            type: string
          description: Identifier returned by `/api/v1/deploy`.
      responses:
        "200":
          description: Task found; returns current status and metadata.
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/DeployStatusResponse'
              examples:
                running:
                  summary: Deployment in progress
                  value:
                    task_id: "fd2c3a1d8f1f4d59b6d3f6c5d30d2f7a"
                    status: "running_build"
                    metadata:
                      branch: "deploy"
                      running_clone:
                        timestamp: "2025-11-05T11:40:00Z"
                        dry_run: true
                      running_build:
                        timestamp: "2025-11-05T11:41:12Z"
                        dry_run: true
                    started_at: "2025-11-05T11:39:58Z"
                    completed_at: null
                    error_log: null
        "404":
          description: Unknown task identifier.
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'
              examples:
                missing:
                  summary: Task not found
                  value:
                    detail: "deploy task not found: 1234"
      security: []
components:
  schemas:
    DeployStatusResponse:
      type: object
      required:
        - task_id
        - status
        - metadata
        - started_at
      properties:
        task_id:
          type: string
          description: Deployment task identifier.
        status:
          type: string
          enum:
            - pending
            - running_clone
            - running_build
            - running_cutover
            - running_observability
            - completed
            - failed
          description: Current task state.
        metadata:
          type: object
          additionalProperties: true
          description: Per-stage metadata captured during execution.
        started_at:
          type: string
          format: date-time
        completed_at:
          type: string
          format: date-time
          nullable: true
        error_log:
          type: string
          nullable: true
          description: Present when `status` is `failed`.
    ErrorResponse:
      type: object
      required:
        - detail
      properties:
        detail:
          type: string
          description: Error message for operators.
