openapi: 3.0.3
info:
  title: Cherry Deploy · Status & Logs API
  version: 1.0.0
  description: |
    배포/롤백 작업의 현재 상태, 최근 히스토리, 단계별 로그를 제공하는 엔드포인트 모음입니다.
servers:
  - url: https://delight.13-125-116-92.nip.io
    description: Production (TLS)
  - url: http://127.0.0.1:9001
    description: 로컬 FastAPI
components:
  securitySchemes:
    AuthCookie:
      type: apiKey
      in: cookie
      name: auth_token
paths:
  /api/v1/status/{task_id}:
    get:
      tags: [deploy]
      summary: 특정 작업의 실시간 상태 조회
      security:
        - AuthCookie: []
      parameters:
        - in: path
          name: task_id
          required: true
          schema:
            type: string
      responses:
        "200":
          description: 작업 상태/메타데이터
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/DeployStatusResponse'
        "404":
          description: Task 미존재
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'
  /api/v1/tasks/recent:
    get:
      tags: [deploy]
      summary: 최근 작업 목록
      security:
        - AuthCookie: []
      parameters:
        - in: query
          name: limit
          schema:
            type: integer
            minimum: 1
            maximum: 20
            default: 5
      responses:
        "200":
          description: 최신 작업 배열
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/DeployTaskSummary'
  /api/v1/tasks/{task_id}/logs:
    get:
      tags: [deploy]
      summary: Stage별 stdout/stderr 스니펫 조회
      security:
        - AuthCookie: []
      parameters:
        - in: path
          name: task_id
          required: true
          schema:
            type: string
      responses:
        "200":
          description: 전체 메타데이터 + stage 로그
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/DeployTaskLogResponse'
        "404":
          description: Task 미존재
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'
components:
  schemas:
    DeployStatusResponse:
      type: object
      required:
        - task_id
        - status
        - metadata
        - stages
        - started_at
      properties:
        task_id:
          type: string
        status:
          type: string
        metadata:
          type: object
          additionalProperties: true
        stages:
          type: object
          additionalProperties:
            type: object
            additionalProperties: true
        started_at:
          type: string
          format: date-time
        completed_at:
          type: string
          format: date-time
          nullable: true
        error_log:
          type: string
          nullable: true
        failure_context:
          type: object
          nullable: true
          additionalProperties: true
        cost_estimate:
          type: object
          nullable: true
          additionalProperties: true
        risk_assessment:
          type: object
          nullable: true
          additionalProperties: true
        llm_preview:
          type: object
          nullable: true
          additionalProperties: true
        blue_green_plan:
          type: object
          nullable: true
          additionalProperties: true
        timezone:
          type: string
    DeployTaskSummary:
      type: object
      required:
        - task_id
        - status
        - branch
        - action
        - started_at
      properties:
        task_id:
          type: string
        status:
          type: string
        branch:
          type: string
        action:
          type: string
        started_at:
          type: string
          format: date-time
        completed_at:
          type: string
          format: date-time
          nullable: true
        actor:
          type: string
          nullable: true
        timezone:
          type: string
          nullable: true
        summary:
          type: object
          nullable: true
          additionalProperties: true
        failure_context:
          type: object
          nullable: true
          additionalProperties: true
    DeployTaskLogResponse:
      type: object
      required:
        - task_id
        - status
        - stages
        - metadata
      properties:
        task_id:
          type: string
        status:
          type: string
        stages:
          type: object
          additionalProperties:
            type: object
            additionalProperties: true
        metadata:
          type: object
          additionalProperties: true
        error_log:
          type: string
          nullable: true
        failure_context:
          type: object
          nullable: true
          additionalProperties: true
    ErrorResponse:
      type: object
      properties:
        detail:
          type: string
