openapi: 3.0.3
info:
  title: Cherry Deploy · Preview API
  version: 1.0.0
  description: |
    배포 전에 실행될 명령, 단계별 ETA, 비용/위험, LLM 요약, Blue/Green 상태를 미리 제공합니다.
servers:
  - url: https://delight.13-125-116-92.nip.io
    description: Production (Nginx)
  - url: http://127.0.0.1:9001
    description: 로컬 FastAPI
components:
  securitySchemes:
    AuthCookie:
      type: apiKey
      in: cookie
      name: auth_token
paths:
  /api/v1/preview:
    get:
      tags: [deploy]
      summary: 다음 배포 시나리오 프리뷰
      description: Git diff(로컬 또는 GitHub Compare) + Gemini 2.5 Flash를 활용해 리스크를 요약합니다.
      security:
        - AuthCookie: []
      parameters:
        - in: query
          name: task_id
          schema:
            type: string
          description: 특정 task에 맞춰 프리뷰를 정렬하고 싶을 때 사용.
      responses:
        "200":
          description: 프리뷰 페이로드
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/DeployPreviewResponse'
        "404":
          description: task_id와 일치하는 작업을 찾을 수 없음
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'
components:
  schemas:
    DeployPreviewResponse:
      type: object
      required:
        - current_branch
        - target_repo
        - commands
        - risk_assessment
        - cost_estimate
        - llm_preview
        - timeline_preview
        - warnings
        - blue_green_plan
        - diff_source
        - diff_stats
      properties:
        current_branch:
          type: string
        target_repo:
          type: string
        frontend_project_path:
          type: string
          nullable: true
        frontend_output_path:
          type: string
          nullable: true
        commands:
          type: array
          items:
            type: string
        risk_assessment:
          type: object
          additionalProperties: true
        cost_estimate:
          type: object
          additionalProperties: true
        llm_preview:
          type: object
          additionalProperties: true
        timeline_preview:
          type: array
          items:
            type: object
            properties:
              stage:
                type: string
              label:
                type: string
              expected_seconds:
                type: integer
              completed:
                type: boolean
              status:
                type: string
                enum: [completed, upcoming, pending]
              metadata:
                type: object
                additionalProperties: true
        warnings:
          type: array
          items:
            type: string
        task_context:
          type: object
          nullable: true
          additionalProperties: true
        blue_green_plan:
          type: object
          properties:
            active_slot:
              type: string
            standby_slot:
              type: string
              nullable: true
            last_cutover_at:
              type: string
              nullable: true
            next_cutover_target:
              type: string
        diff_source:
          type: string
          enum: [working_tree, github_compare]
        diff_stats:
          type: object
          additionalProperties: true
        compare_metadata:
          type: object
          nullable: true
          additionalProperties: true
    ErrorResponse:
      type: object
      properties:
        detail:
          type: string
